// Convert DB row → frontend User shape (camelCase, hide passwords)
export const formatUser = (row: any) => ({
  id: row.id,
  name: row.name,
  email: row.email,
  password: '***',
  loginPin: '***',
  phone: row.phone,
  address: row.address,
  city: row.city,
  country: row.country,
  dateOfBirth: row.date_of_birth,
  gender: row.gender,
  occupation: row.occupation,
  profileImage: row.profile_image,
  balance: parseFloat(row.balance) || 0,
  totalInvested: parseFloat(row.total_invested) || 0,
  totalEarnings: parseFloat(row.total_earnings) || 0,
  totalWithdrawn: parseFloat(row.total_withdrawn) || 0,
  referralCode: row.referral_code,
  referredBy: row.referred_by,
  referralCount: row.referral_count || 0,
  referralBonusPercentage: parseFloat(row.referral_bonus_percentage) || 0,
  referralEarnings: parseFloat(row.referral_earnings) || 0,
  referralLevel2Count: row.referral_level2_count || 0,
  joinedDate: row.joined_date || row.created_at,
  isBlocked: row.is_blocked,
  kycStatus: row.kyc_status || 'none',
  twoFactorEnabled: row.two_factor_enabled,
  isAdmin: row.is_admin,
  walletAddress: row.wallet_address,
});
